### ISSUE TITLE
Meteor cannot start when using with nami

### ISSUE THREAD

**Issue by vhmh2005** [marcelog/Nami#37]
I am using npm nami package inside Meteor app to listen to events from an Asterisk server. In server side, I have this code:

```
namiLib = Meteor.npmRequire "nami"
namiConfig =
    "host": "..."
    "port": 5038
    "username": "..."
    "secret": "...
nami = new namiLib.Nami namiConfig
```

If I remove the line nami = new namiLib.Nami namiConfig, the server runs fine. But with that line, the server stops at following step, and I cannot access http://localhost:3000, which is the default url for Meteor app. Nami package prevents Meteor from starting.

![](http://i.stack.imgur.com/8djV4.png)

Any idea to help resolve this issue?

I have posted this question on Stackoverflow but still no solution except using other package instead of nami.

http://stackoverflow.com/questions/28430613/meteor-cannot-start-when-using-meteorhacksnpm-nami-package-cannot-access-loca/28445368?noredirect=1#comment45222484_28445368

**Comment by marcelog** [comment]
Hello. I have to close this one until there's a clear sign of an issue in Nami itself and not in your code or meteor. Feel free to reopen it with specific details if you think this is a nami issue.

**Comment by vhmh2005** [comment]
I used other package, e.g., asterisk-manager and it works fine. Seems that Nami has blocked other execution.

**Comment by marcelog** [comment]
I'm not a meteor user, so perhaps you could try to debug and find out what could be wrong
