### ISSUE TITLE
How to disable debug logging

### ISSUE THREAD

**Issue by darksaboteur** [marcelog/Nami#41]
When using the library there are get many debug log events printed to the console like the following:
[2016-02-26 11:47:56.036] [DEBUG] Nami.Client - Got event: Event { .....
[2016-02-26 11:47:56.036] [DEBUG] Nami.Client - Skipped 0 bytes

repeated thousands of times.

How do are these disabled?

**Comment by marcelog** [comment]
Hello,

Nami uses log4js, you should check their doc: https://github.com/nomiddlename/log4js-node

The AsterTrace-Node project has also an example for setting this up: https://github.com/marcelog/AsterTrace-Node/blob/master/conf/logger.json.example

Best!

**Comment by NicolasCharpentier** [comment]
Hi,

Was also looking for this.

You can use the null object pattern.

`var nami = new (namiLib.Nami)(namiConfObject);`

`nami.logger = {
  debug: function () {}
};`
