### ISSUE TITLE
PJsip Actions

### ISSUE THREAD

**Issue by jbas** [marcelog/Nami#43]
How about PJSIP actions?

PJSIPNotify
PJSIPQualify
PJSIPRegister
PJSIPShowEndpoint
PJSIPShowEndpoints
PJSIPShowRegistrationsInbound
PJSIPShowRegistrationsOutbound
PJSIPShowResourceLists
PJSIPShowSubscriptionsInbound
PJSIPShowSubscriptionsOutbound
PJSIPUnregister

Thanks, Jesús

**Comment by marcelog** [comment]
Hello!

Sure, that would be great! Feel free to open a pull request for them.

Cheers!

**Comment by jbas** [comment]
Work on it. Thank you.
