### ISSUE TITLE
Error on the QuickStart example

### ISSUE THREAD

**Issue by digas** [marcelog/Nami#48]
Hey, is just me or there is no definition of namiLib  on the code ?
Tried to implement the simple quickstart example and (the user on manager is ok so i know it can login) node complians with this.... can you give me a light ?
thanks
  
 nami.send(new namiLib.Actions.CoreShowChannelsAction(), function(response){
                                ^
ReferenceError: namiLib is not defined

sorry let me give you some versions:
nami 0.7.1
node v4.4.0 (and tested it on v0.12.2 too)
Asterisk 11.21.0

**Comment by digas** [comment]
Ok just forget it , i found the answer on the index.js file
following the example there , 

var namiLib = require(__dirname + "node_modules/nami/src/nami.js");

Anyway i believe this should be mention on the example code too or else people will have the same problem again

**Comment by marcelog** [comment]
You should:

```js
var namiLib = require('nami');
```

Once nami is in your package.json. The example also works fine:
```bash
node src/index.js 127.0.0.1 5038 user secret
```

**Comment by digas** [comment]
Please confirm me this on the example you try to call a function :
nami.send( new namiLib.Actions.**CoreShowChannelsAction**(),

But i only found on messages/actions.js CoreShowChannels() function and if i change it on the example it works ... is it ok ?
